package:
  name: ixtlilton
  version: "{{ environ['GIT_DESCRIBE_TAG'] }}"
source:
  path: ../../
build:
  number: 1
requirements:
  build:
  - python
  - setuptools
  - numpy
  run:
  - python
  - pandas
  - numpy
about:
  home: https://uibcdf.org
  license: MIT License
  summary: ''
  description: 'This library provides some tools to work with Ixtlilton

    '
  dev_url: https://github.com/uibcdf/Ixtlilton
  doc_url: https://uibcdf.org/Ixtlilton
