name: Build and upload conda packages

on:
  release:
    types: ['released', 'prereleased']

  workflow_dispatch:

jobs:
  conda_deployment_with_new_tag:
    name: Conda deployment of package to platform ubuntu-latest with Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Additional info about the build
      shell: bash
      run: |
        uname -a

    - name: Conda environment creation and activation
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        environment-file: devtools/conda-envs/build_env.yaml    # Path to the build conda environment
        auto-update-conda: false
        auto-activate-base: false
        show-channel-urls: true

    - name: Build and upload the conda packages
      uses: uibcdf/action-build-and-upload-conda-packages@v1.1-beta.1
      with:
        meta_yaml_dir: devtools/conda-build
        python-version: ${{ matrix.python-version }} # Values previously defined in `matrix`
        user: uibcdf
        label: auto
        token: ${{ secrets.ANACONDA_UIBCDF_TOKEN }} # Replace with the right name of your secret

